name: hali_stawi
description: Personal Health Mngt App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  intl:
  flutter:
    sdk: flutter
  http: ^0.13.5
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.1.0
  flutter_offline: ^2.1.0
  material_design_icons_flutter: ^6.0.7096
  floating_bottom_navigation_bar: ^1.5.2
  shimmer: ^3.0.0
  shared_preferences: ^2.1.1
  modal_progress_hud_nsn: ^0.3.0
  google_fonts: ^4.0.4
  fluttertoast: ^8.2.2
  strings: ^1.0.0
  carousel_pro: ^1.0.0
  flutter_html: ^2.2.1
  image_picker: ^0.8.7
  cupertino_icons: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  carousel_slider: ^3.0.0
  rename: ^1.3.1
  rxdart: ^0.27.0
  modal_progress_hud: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
